LANGUAGES = {
    "English only": "en",
    "Spanish": "es",
    "Hindi": "hi",
    "Arabic": "ar",
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Bengali": "bn",
    "Urdu": "ur",
    "French": "fr",
    "Portuguese": "pt",
    "Vietnamese": "vi",
    "Tagalog / Filipino": "tl",
    "Haitian Creole": "ht",
    "Korean": "ko",
    "Russian": "ru",
    "Ukrainian": "uk",
    "Swahili": "sw",
    "Amharic": "am",
    "Quechua": "qu",
    "Nahuatl": "nah",
}
